"""
Tool: get_scraped_data

Fetches stock data from local JSON files scraped from Screener.in.
"""

import json
import os
from pathlib import Path

def get_scraped_data(ticker: str) -> dict:
    """
    Get comprehensive stock data (financials, ratios, etc.) from local JSON files.
    These files are generated by the screener scraper.

    Args:
        ticker: Stock ticker symbol (e.g., 'RELIANCE', 'TCS', 'INFY')
               Note: If .NS suffix is provided, it will be stripped.

    Returns:
        Dictionary containing comprehensive stock data or an error message.
    """
    # Clean up ticker (remove .NS or .BO suffix)
    symbol = ticker.split('.')[0].upper()
    
    # Path to the data directory (assuming it's in the project root)
    # We'll try a few common locations relative to the package structure
    data_dir = Path("data")
    if not data_dir.exists():
        # Try absolute path based on the user's workspace if relative fails
        workspace_root = Path("/Users/jiteshbhati/Projects/Sharelock")
        data_dir = workspace_root / "data"

    json_path = data_dir / f"{symbol}_data.json"
    
    if not json_path.exists():
        return {
            "error": f"No scraped data found for '{symbol}'. Please run the scraper first.",
            "ticker": symbol,
            "tried_path": str(json_path)
        }
    
    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return data
    except Exception as e:
        return {
            "error": f"Failed to read data for '{symbol}': {str(e)}",
            "ticker": symbol
        }
